# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Teaching
    url: teaching/
    weight: 11
  - name: Awards
    url: awards/  
    weight: 12
  - name: Research
    url: research/
    weight: 13
  - name: Publications
    url: publications/
    weight: 14
  - name: Students
    url: students/
    weight: 15
